version: '3'
services:
  db:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: 'neo4j/neo4j_test'
      NEO4JLABS_PLUGINS: '["apoc"]'
  #   ports are no need to be exposed, as app can access db within docker network
  #    ports:
  #      - "7474:7474"
  #      - "7687:7687"
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      DB_URI: 'bolt://db:7687'
      DB_USER: 'neo4j'
      DB_PASSWORD: 'neo4j_test'
    command: ['npm', 'run', 'test']
